# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   phoenix:
      # The build parameters for this container.
      build:
         # Here we define that it should build from the current directory.
         context: .
         dockerfile: Dockerfile
      environment:
         # Variables to connect to our Postgres server.
         PGUSER: 'postgres'
         PGPASSWORD: 'password'
         PGDATABASE: 'datahub'   
         PGPORT: '5432'
         # Hostname of our Postgres container.
         PGHOST: postgres
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '4000:4000'
      depends_on:
         # The DB container needs to be started before we start this container.
         - postgres

   postgres:
      image: postgres:12.9-alpine
      container_name: postgres
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=datahub
      ports:
         - 5433:5432
      volumes:
         - ./db:/docker-entrypoint-initdb.d/
      restart: on-failure:10
      
volumes:
   database-data: